### ISSUE TITLE
Installer CLI not searching for plugins correctly

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/modular-file-renderer#122]
When I run `mfr install all`, it appears that the CLI is not searching for plugins correctly. Here's what I get when I have my osf virtualenv enabled. 

```
$ mfr install all
Plugin with name "_billiard.so" not found. Skipping...
Plugin with name "_regex.so" not found. Skipping...
Plugin with name "_regex_core.py" not found. Skipping...
Plugin with name "_regex_core.pyc" not found. Skipping...
Plugin with name "argparse.py" not found. Skipping...
Plugin with name "argparse.pyc" not found. Skipping...
Plugin with name "backports.ssl_match_hostname-3.4.0.2-py2.7.egg-info" not found. Skipping...
Plugin with name "cssmin.py" not found. Skipping...
Plugin with name "cssmin.pyc" not found. Skipping...
Plugin with name "dataverse.egg-link" not found. Skipping...
Plugin with name "decorator.py" not found. Skipping...
Plugin with name "decorator.pyc" not found. Skipping...
Plugin with name "docopt.py" not found. Skipping...
Plugin with name "docopt.pyc" not found. Skipping...
Plugin with name "easy-install.pth" not found. Skipping...
Plugin with name "easy_install.py" not found. Skipping...
Plugin with name "easy_install.pyc" not found. Skipping...
Plugin with name "gig.py" not found. Skipping...
Plugin with name "gig.pyc" not found. Skipping...
Plugin with name "gnupg.py" not found. Skipping...
Plugin with name "gnupg.pyc" not found. Skipping...
Plugin with name "gnureadline.so" not found. Skipping...
Plugin with name "hurry.filesize-0.9-py2.7-nspkg.pth" not found. Skipping...
Plugin with name "ipython-2.1.0-py2.7.egg-info" not found. Skipping...
Plugin with name "itsdangerous.py" not found. Skipping...
Plugin with name "itsdangerous.pyc" not found. Skipping...
Plugin with name "magic.py" not found. Skipping...
Plugin with name "magic.pyc" not found. Skipping...
Plugin with name "mailchimp.py" not found. Skipping...
Plugin with name "mailchimp.pyc" not found. Skipping...
Plugin with name "mccabe.py" not found. Skipping...
Plugin with name "mccabe.pyc" not found. Skipping...
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.6 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_code_pygments/render-requirements.txt (line 1))
Collecting git+https://github.com/mfraezz/pydocx.git (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_docx/render-requirements.txt (line 1))
  Cloning https://github.com/mfraezz/pydocx.git to /var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-IwFdds-build
  Requirement already satisfied (use --upgrade to upgrade): PyDocX==0.4.2 from git+https://github.com/mfraezz/pydocx.git in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_docx/render-requirements.txt (line 1))
Collecting git+https://github.com/jsocol/bleach.git (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_docx/render-requirements.txt (line 2))
  Cloning https://github.com/jsocol/bleach.git to /var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-etWMAq-build
  Requirement already satisfied (use --upgrade to upgrade): bleach==1.4.1 from git+https://github.com/jsocol/bleach.git in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_docx/render-requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from bleach==1.4.1->-r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_docx/render-requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): html5lib>=0.999 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from bleach==1.4.1->-r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_docx/render-requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Pillow>=2.3.0 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_image/export-requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): ipython>=2.1.0 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_ipynb/render-requirements.txt (line 1))
Collecting git+https://github.com/biasmv/pv.git (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_pdb/render-requirements.txt (line 1))
  Cloning https://github.com/biasmv/pv.git to /var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-ocqf8P-build
    Traceback (most recent call last):
      File "<string>", line 18, in <module>
    IOError: [Errno 2] No such file or directory: '/var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-ocqf8P-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 18, in <module>

    IOError: [Errno 2] No such file or directory: '/var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-ocqf8P-build/setup.py'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-ocqf8P-build
    Collecting git+https://github.com/mstamy2/PyPDF2.git (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_pdf/render-requirements.txt (line 1))
      Cloning https://github.com/mstamy2/PyPDF2.git to /var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-UFSstU-build
      Requirement already satisfied (use --upgrade to upgrade): PyPDF2==1.24 from git+https://github.com/mstamy2/PyPDF2.git in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_pdf/render-requirements.txt (line 1))
    Requirement already satisfied (use --upgrade to upgrade): mako in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_pdf/render-requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from mako->-r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_pdf/render-requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): Docutils>=0.11 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_rst/render-requirements.txt (line 1))
    Collecting git+https://github.com/icereval/xlrd.git (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_tabular/render-requirements.txt (line 1))
      Cloning https://github.com/icereval/xlrd.git to /var/folders/kd/9_jv37r94035mc9b94b3f_6c0000gn/T/pip-2Fe9Th-build
      Requirement already satisfied (use --upgrade to upgrade): xlrd==0.9.3 from git+https://github.com/icereval/xlrd.git in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_tabular/render-requirements.txt (line 1))
    Requirement already satisfied (use --upgrade to upgrade): pandas>=0.14.1 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from -r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_tabular/render-requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from pandas>=0.14.1->-r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_tabular/render-requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from pandas>=0.14.1->-r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_tabular/render-requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.1 in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from pandas>=0.14.1->-r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_tabular/render-requirements.txt (line 2))
    Requirement already satisfied (use --upgrade to upgrade): six in /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages (from python-dateutil->pandas>=0.14.1->-r /Users/sloria/miniconda/envs/osf/lib/python2.7/site-packages/mfr/../mfr_tabular/render-requirements.txt (line 2))
Plugin with name "mock.py" not found. Skipping...
Plugin with name "mock.pyc" not found. Skipping...
Plugin with name "os_networksv2_python_novaclient_ext.py" not found. Skipping...
Plugin with name "os_networksv2_python_novaclient_ext.pyc" not found. Skipping...
Plugin with name "os_virtual_interfacesv2_python_novaclient_ext.py" not found. Skipping...
Plugin with name "os_virtual_interfacesv2_python_novaclient_ext.pyc" not found. Skipping...
Plugin with name "oslo.config-1.4.0-py2.7-nspkg.pth" not found. Skipping...
Plugin with name "oslo.i18n-1.0.0-py2.7-nspkg.pth" not found. Skipping...
Plugin with name "oslo.serialization-1.0.0-py2.7-nspkg.pth" not found. Skipping...
Plugin with name "oslo.utils-1.0.0-py2.7-nspkg.pth" not found. Skipping...
Plugin with name "pep8.py" not found. Skipping...
Plugin with name "pep8.pyc" not found. Skipping...
Plugin with name "PIL.pth" not found. Skipping...
Plugin with name "prettytable.py" not found. Skipping...
Plugin with name "prettytable.pyc" not found. Skipping...
Plugin with name "pytest.py" not found. Skipping...
Plugin with name "pytest.pyc" not found. Skipping...
Plugin with name "pyzmq-14.3.1-py2.7.egg-info" not found. Skipping...
Plugin with name "readline.py" not found. Skipping...
Plugin with name "readline.pyc" not found. Skipping...
Plugin with name "README" not found. Skipping...
Plugin with name "rednose.py" not found. Skipping...
Plugin with name "rednose.pyc" not found. Skipping...
Plugin with name "regex.py" not found. Skipping...
Plugin with name "regex.pyc" not found. Skipping...
Plugin with name "responses.py" not found. Skipping...
Plugin with name "responses.pyc" not found. Skipping...
Plugin with name "setuptools-7.0-py2.7.egg" not found. Skipping...
Plugin with name "setuptools.pth" not found. Skipping...
Plugin with name "six.py" not found. Skipping...
Plugin with name "six.pyc" not found. Skipping...
Plugin with name "sword2.egg-link" not found. Skipping...
Plugin with name "termstyle.py" not found. Skipping...
Plugin with name "termstyle.pyc" not found. Skipping...
Plugin with name "test_regex.py" not found. Skipping...
Plugin with name "test_regex.pyc" not found. Skipping...
Plugin with name "tornado-3.2.2-py2.7.egg-info" not found. Skipping...
Plugin with name "uwsgidecorators.py" not found. Skipping...
Plugin with name "uwsgidecorators.pyc" not found. Skipping...
Plugin with name "version.py" not found. Skipping...
Plugin with name "version.pyc" not found. Skipping...
```

The failure to install Pillow may be an unrelated issue.

**Comment by mfraezz** [comment]
Well, PV fails to install because that project doesn't have a setup.py [https://github.com/biasmv/pv/], though all that's actually needed to render is contained in the <code>mfr_pdb/static/</code> directory; that requirement can probably be removed. <code>mfr install all</code> does find all the plugins, but I agree that it checks far too many files. If it's safe to assume that any future MFR modules will continue the <code>mfr_[module_name]/[render | export]_requirements.txt</code> naming convention, this is an easy refactor
