### ISSUE TITLE
 add endpoints to return information on supported exporters

### ISSUE THREAD

**Issue by rija** [CenterForOpenScience/modular-file-renderer#254]
**User story:**

As a developer working on an application that depends o MFR
I want to query MFR for a format 
So that my application can choose wether to use MFR based on wether MFR can export from that format

**Acceptance tests:**

> Given that MFR has an endpoint listing supported format for export  ``/exporters``
> When my application query that endpoint
> Then a JSON output listing all the supported (format,exporter class) pairs  is returned

```
HTTP/1.1 200 OK
{
	…
	“pptx” : ”mfr.extensions.unoconv:UnoconvExporter”,
	“psw” : “mfr.extensions.unoconv:UnoconvExporter”,
	…
}
```

> Given that MFR has an endpoint listing export information for the format __pptx__  ``/exporters/pptx``
> And __pptx__ is a format supported by MFR for export
> When my application query that endpoint
> Then a JSON output of the  matching pairs format/exporter  class  is returned

```
HTTP/1.1 200 OK
{
	“pptx” : ”mfr.extensions.unoconv:UnoconvExporter”
}
```

> Given that MFR has an endpoint listing export information for the format __fastq__  ``/exporters/fastq``
> And __fastq__ is __not__ a supported format for export
> When my application query that endpoint
> Then 404 Resource Not Found response is returned

```
HTTP/1.1 404 Not Found
```

**Comment by rija** [comment]
**Questions:**
Although the intent of this feature request is about knowing whether my application can defer to MFR for rendering the preview or not, I'd like to know how the routing to  a particular exporter/renderer happens. 
I was under the (probably naive) impression that the exporters and renderer list in [setup.py](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/setup.py) is where we route an extension to a renderer or a exporter. 

It's based on that assumption that I've formulated the feature request as I did. 

However I was trying to change the routing of '.xsl' and commented out the lines associated to TabularRenderer and uncommented the one associated with unoconv renderer.

Also updated the settings in unoconv extension to have something like this:

```
RENDER_MAP = config.get('RENDER_MAP', {
     'csv': {'renderer': '.xlsx', 'format': 'xlsx'},
     'xls': {'renderer': '.xlsx', 'format': 'xlsx'},
     'ppt': {'renderer': '.pdf', 'format': 'pdf'},
     'pptx': {'renderer': '.pdf', 'format': 'pdf'},
})
```

however, after restarting MFR,  feeding the system with an (supposedly malformed)  *.xls file seems to indicate that the Tabular Renderer is still used:

```
2017-04-29 08:24:46 [96] | HTTPServerRequest(protocol='http', host='x.x.x.x:7778', method='GET', uri='/render?url=https://gigadb-bundles-test.s3.amazonaws.com/Mongolia_Human.function.statistics.xls', version='HTTP/1.1', remote_ip='y.y.y.y', headers={'Referer': 'http://127.0.0.1:9170/dataset/view/id/100104', 'Host': 'x.x.x.x:7778', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8', 'Upgrade-Insecure-Requests': '1', 'Accept-Language': 'en-us', 'Dnt': '1', 'Connection': 'keep-alive'})
2017-04-29 08:24:46 [96] | Traceback (most recent call last):
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1445, in _execute
2017-04-29 08:24:46 [96] |     result = yield result
2017-04-29 08:24:46 [96] |   File 
2017-04-29 08:24:46 [96] | "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
2017-04-29 08:24:46 [96] |     value = future.result()
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
2017-04-29 08:24:46 [96] |     raise_exc_info(self._exc_info)
2017-04-29 08:24:46 [96] |   File "<string>", line 3, in raise_exc_info
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
2017-04-29 08:24:46 [96] |     yielded = self.gen.throw(*exc_info)
2017-04-29 08:24:46 [96] |   File "<string>", line 6, in _wrap_awaitable
2017-04-29 08:24:46 [96] |   File "/code/mfr/server/handlers/render.py", line 69, in get
2017-04-29 08:24:46 [96] |     rendition = await loop.run_in_executor(None, renderer.render)
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/asyncio/futures.py", line 380, in __iter__
2017-04-29 08:24:46 [96] |     yield self  # This tells Task to wait for completion.
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
2017-04-29 08:24:46 [96] |     value = future.result()
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
2017-04-29 08:24:46 [96] |     raise_exc_info(self._exc_info)
2017-04-29 08:24:46 [96] |   File "<string>", line 3, in raise_exc_info
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/concur
2017-04-29 08:24:46 [96] | rent/futures/thread.py", line 55, in run
2017-04-29 08:24:46 [96] |     result = self.fn(*self.args, **self.kwargs)
2017-04-29 08:24:46 [96] |   File "/code/mfr/extensions/tabular/render.py", line 20, in render
2017-04-29 08:24:46 [96] |     sheets, size = self._render_grid(fp, self.metadata.ext)
2017-04-29 08:24:46 [96] |   File "/code/mfr/extensions/tabular/render.py", line 44, in _render_grid
2017-04-29 08:24:46 [96] |     sheets = self._populate_data(fp, ext)
2017-04-29 08:24:46 [96] |   File "/code/mfr/extensions/tabular/render.py", line 76, in _populate_data
2017-04-29 08:24:46 [96] |     return imported(fp)
2017-04-29 08:24:46 [96] |   File "/code/mfr/extensions/tabular/libs/xlrd_tools.py", line 16, in xlsx_xlrd
2017-04-29 08:24:46 [96] |     wb = xlrd.open_workbook(fp.name)
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/xlrd/__init__.py", line 441, in open_workbook
2017-04-29 08:24:46 [96] |     ragged_rows=ragged_rows,
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/xlrd/book.py", line 91, in open_workbook_xls
2017-04-29 08:24:46 [96] |     biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/xlrd/book.py", line 1230, in getbof
2017-04-29 08:24:46 [96] |     bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
2017-04-29 08:24:46 [96] |   File "/usr/local/lib/python3.5/site-packages/xlrd/
2017-04-29 08:24:46 [96] | book.py", line 1224, in bof_error
2017-04-29 08:24:46 [96] |     raise XLRDError('Unsupported format, or corrupt file: ' + msg)
2017-04-29 08:24:46 [96] | xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'\tNumber\t'


```

**Comment by felliott** [comment]
Hey @rija!

After you update `setup.py`, you'll need to re-run `invoke install` to make sure the new routes are registered.  And :+1: to an endpoint for listing the supported exporters and renderers.  Are you already working on a PR for this?  If not, I'll create a ticket for it internally and see if one of our devs can pick it up in the next few sprints.

Cheers,
@felliott

**Comment by felliott** [comment]
@Johnetordoff has submitted a PR to support this, which we should be reviewing soon.  I'll ping again here when it's merged.

**Comment by felliott** [comment]
Hey @rija,

This was added in the v0.23 release of MFR.  We've added two endpoints (`/renderers` and `/exporters`) to make this programmatically available, and some [static documentation](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/supportedextensions.md) as well.

Cheers,
@felliott

**Comment by rija** [comment]
@felliott

Thank you very much for this!
The contract work I was doing that I specified this feature for has not gone to production yet.
If I can get my task back onto my next batch of work, I'll see to implement this and remove the workarounds.

In the meantime, I'll have a play at the api shortly.
